# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dotnet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.x
    - name: Version (release)
      run: |
        OLD=$(yq ".Project.PropertyGroup[0].Version" -p xml -o xml src/pingmint.azuredevops/pingmint.azuredevops.csproj)
        NEW="$OLD.${COUNTER}" yq ".Project.PropertyGroup[0].Version = env(NEW)" -p xml -o xml -i src/pingmint.azuredevops/pingmint.azuredevops.csproj
        cat src/pingmint.azuredevops/pingmint.azuredevops.csproj
      env:
        COUNTER: ${{ github.run_number }}
      if: github.ref == 'refs/heads/main'
    - name: Version (pre-release)
      run: |
        OLD=$(yq ".Project.PropertyGroup[0].Version" -p xml -o xml src/pingmint.azuredevops/pingmint.azuredevops.csproj)
        NEW="$OLD.${COUNTER}" yq ".Project.PropertyGroup[0].Version = env(NEW)" -p xml -o xml -i src/pingmint.azuredevops/pingmint.azuredevops.csproj
        cat src/pingmint.azuredevops/pingmint.azuredevops.csproj
      env:
        COUNTER: ${{ github.run_number }}
      if: github.ref != 'refs/heads/main'
    - name: Restore dependencies
      run: dotnet restore src/pingmint.azuredevops
    - name: Build
      run: dotnet build --configuration Release --no-restore src/pingmint.azuredevops
    - name: Test
      run: dotnet test --configuration Release --no-build --no-restore --verbosity normal src/pingmint.azuredevops
    - name: Pack
      run: dotnet pack --configuration Release --no-build --no-restore --verbosity normal --output ./nupkg src/pingmint.azuredevops
    - name: Push
      run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key $NUGET_API_KEY
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      #if: github.ref == 'refs/heads/main'
